import {useCallback, useEffect, useMemo, useState} from 'react';
import {useMutation} from '@tanstack/react-query';
import {z} from 'zod';

import {Alert} from '@sentry/scraps/alert';
import {Button} from '@sentry/scraps/button';
import {
  defaultFormOptions,
  FieldGroup as FormPanel,
  useScrapsForm,
} from '@sentry/scraps/form';
import {Flex, Stack} from '@sentry/scraps/layout';
import {Text} from '@sentry/scraps/text';

import {
  addErrorMessage,
  addLoadingMessage,
  addSuccessMessage,
} from 'sentry/actionCreators/indicator';
import {openRecoveryOptions} from 'sentry/actionCreators/modal';
import {
  fetchOrganizationByMember,
  fetchOrganizations,
} from 'sentry/actionCreators/organizations';
import {NotFound} from 'sentry/components/errors/notFound';
import type {Field} from 'sentry/components/forms/types';
import {LoadingError} from 'sentry/components/loadingError';
import {LoadingIndicator} from 'sentry/components/loadingIndicator';
import {QuietZoneQRCode} from 'sentry/components/quietZoneQRCode';
import {SentryDocumentTitle} from 'sentry/components/sentryDocumentTitle';
import {TextCopyInput} from 'sentry/components/textCopyInput';
import {WebAuthnEnroll} from 'sentry/components/webAuthn/webAuthnEnroll';
import {t} from 'sentry/locale';
import {OrganizationsStore} from 'sentry/stores/organizationsStore';
import type {
  Authenticator,
  SmsAuthenticator,
  TotpAuthenticator,
  U2fAuthenticator,
} from 'sentry/types/auth';
import {generateOrgSlugUrl} from 'sentry/utils';
import {getApiUrl} from 'sentry/utils/api/getApiUrl';
import {getPendingInvite} from 'sentry/utils/getPendingInvite';
import {fetchMutation, useApiQuery} from 'sentry/utils/queryClient';
import {testableWindowLocation} from 'sentry/utils/testableWindowLocation';
import {useApi} from 'sentry/utils/useApi';
import {useNavigate} from 'sentry/utils/useNavigate';
import {useParams} from 'sentry/utils/useParams';
import {RemoveConfirm} from 'sentry/views/settings/account/accountSecurity/components/removeConfirm';
import {SettingsPageHeader} from 'sentry/views/settings/components/settingsPageHeader';
import {TextBlock} from 'sentry/views/settings/components/text/textBlock';

import {AuthenticatorHeader} from './components/authenticatorHeader';

/**
 * Payloads submitted to the enroll endpoint. The exact shape depends on the
 * authenticator type being enrolled.
 */
type EnrollPayload =
  | {otp: string; secret: string | undefined}
  | {otp: string | undefined; phone: string; secret: string | undefined}
  | {challenge: string; deviceName: string; response: string};

/**
 * The enroll form fields are generated by the server. Read the label/default
 * for a given field by name so we preserve the server-provided copy.
 */
function getServerField(form: Field[] | undefined, name: string) {
  return form?.find(field => field.name === name);
}

function getServerFieldLabel(form: Field[] | undefined, name: string): React.ReactNode {
  const label = getServerField(form, name)?.label;
  return typeof label === 'function' ? label() : label;
}

function getServerFieldDefault(form: Field[] | undefined, name: string): string {
  const defaultValue = getServerField(form, name)?.defaultValue;
  return typeof defaultValue === 'string' ? defaultValue : '';
}

/**
 * TOTP enrollment: show the QR code + secret, collect the OTP code.
 */
function TotpEnrollForm({
  authenticator,
  onSubmit,
}: {
  authenticator: TotpAuthenticator;
  onSubmit: (value: {otp: string}) => void;
}) {
  const form = useScrapsForm({
    ...defaultFormOptions,
    defaultValues: {otp: getServerFieldDefault(authenticator.form, 'otp')},
    validators: {onDynamic: z.object({otp: z.string()})},
    onSubmit: ({value}) => onSubmit(value),
  });

  return (
    <form.AppForm form={form}>
      <FormPanel title={t('Configuration')}>
        <Flex justify="center">
          <QuietZoneQRCode
            aria-label={t('Enrollment QR Code')}
            value={authenticator.qrcode}
            size={228}
          />
        </Flex>

        <Stack gap="xs">
          <Text bold size="sm">
            {t('Authenticator secret')}
          </Text>
          <TextCopyInput>{authenticator.secret ?? ''}</TextCopyInput>
        </Stack>

        <form.AppField name="otp">
          {field => (
            <field.Layout.Row label={getServerFieldLabel(authenticator.form, 'otp')}>
              <field.Input
                value={field.state.value}
                onChange={field.handleChange}
                autoComplete="off"
              />
            </field.Layout.Row>
          )}
        </form.AppField>

        <Flex justify="end">
          <form.SubmitButton>{t('Confirm')}</form.SubmitButton>
        </Flex>
      </FormPanel>
    </form.AppForm>
  );
}

/**
 * SMS enrollment: a two step flow. First a phone number is submitted to send
 * an OTP, then the received OTP is submitted for verification.
 */
function SmsEnrollForm({
  authenticator,
  hasSentCode,
  sendingCode,
  onReset,
  onSubmit,
}: {
  authenticator: SmsAuthenticator;
  hasSentCode: boolean;
  onReset: () => void;
  onSubmit: (value: {otp: string; phone: string}, formApi: {reset: () => void}) => void;
  sendingCode: boolean;
}) {
  const schema = useMemo(
    () =>
      z.object({
        phone: z.string().min(1),
        otp: hasSentCode ? z.string().min(1) : z.string(),
      }),
    [hasSentCode]
  );

  const form = useScrapsForm({
    ...defaultFormOptions,
    defaultValues: {
      phone: authenticator.phone ?? getServerFieldDefault(authenticator.form, 'phone'),
      otp: getServerFieldDefault(authenticator.form, 'otp'),
    },
    validators: {onDynamic: schema},
    onSubmit: ({value, formApi}) => onSubmit(value, formApi),
  });

  return (
    <form.AppForm form={form}>
      <FormPanel title={t('Configuration')}>
        <form.AppField name="phone">
          {field => (
            <field.Layout.Row label={getServerFieldLabel(authenticator.form, 'phone')}>
              <field.Input
                value={field.state.value}
                onChange={field.handleChange}
                disabled={sendingCode || hasSentCode}
                autoComplete="off"
              />
            </field.Layout.Row>
          )}
        </form.AppField>

        {hasSentCode && (
          <form.AppField name="otp">
            {field => (
              <field.Layout.Row
                label={getServerFieldLabel(authenticator.form, 'otp')}
                required
              >
                <field.Input
                  value={field.state.value}
                  onChange={field.handleChange}
                  autoComplete="off"
                />
              </field.Layout.Row>
            )}
          </form.AppField>
        )}

        <Flex justify="end" align="center" gap="md">
          {hasSentCode && <Button onClick={onReset}>{t('Start Over')}</Button>}
          <form.SubmitButton>
            {hasSentCode ? t('Confirm') : t('Send Code')}
          </form.SubmitButton>
        </Flex>
      </FormPanel>
    </form.AppForm>
  );
}

/**
 * U2F / WebAuthn enrollment: enroll a device via the browser, then name it.
 */
function U2fEnrollForm({
  authenticator,
  onSubmit,
}: {
  authenticator: U2fAuthenticator;
  onSubmit: (value: {challenge: string; deviceName: string; response: string}) => void;
}) {
  const [webAuthnData, setWebAuthnData] = useState<{
    challenge: string;
    response: string;
  } | null>(null);
  const [enrollError, setEnrollError] = useState<string | null>(null);

  const form = useScrapsForm({
    ...defaultFormOptions,
    defaultValues: {
      deviceName: getServerFieldDefault(authenticator.form, 'deviceName'),
    },
    validators: {onDynamic: z.object({deviceName: z.string()})},
    onSubmit: ({value}) => {
      if (!webAuthnData) {
        setEnrollError(t('Please enroll your device before continuing.'));
        return;
      }
      onSubmit({...webAuthnData, deviceName: value.deviceName});
    },
  });

  return (
    <form.AppForm form={form}>
      <FormPanel title={t('Configuration')}>
        <Stack gap="xs">
          <Text bold size="sm">
            {t('Enroll Device')}
          </Text>
          <Text variant="muted" size="sm">
            {t('Enroll your Passkey, Security Key, or Biometric authenticator.')}
          </Text>
          <WebAuthnEnroll
            challengeData={authenticator.challenge}
            onEnroll={data => {
              setWebAuthnData(data);
              setEnrollError(null);
            }}
          />
          {enrollError && (
            <Text variant="danger" size="sm">
              {enrollError}
            </Text>
          )}
        </Stack>

        <form.AppField name="deviceName">
          {field => (
            <field.Layout.Row
              label={getServerFieldLabel(authenticator.form, 'deviceName')}
            >
              <field.Input
                value={field.state.value}
                onChange={field.handleChange}
                autoComplete="off"
              />
            </field.Layout.Row>
          )}
        </form.AppField>

        <Flex justify="end">
          <form.SubmitButton>{t('Confirm')}</form.SubmitButton>
        </Flex>
      </FormPanel>
    </form.AppForm>
  );
}

/**
 * Renders necessary forms in order to enroll user in 2fa
 */
export default function AccountSecurityEnroll() {
  const api = useApi();
  const {authId} = useParams<{authId: string}>();
  const navigate = useNavigate();

  const [hasSentCode, setHasSentCode] = useState(false);
  const [sendingCode, setSendingCode] = useState(false);
  const [isMutationPending, setIsMutationPending] = useState(false);

  const authenticatorEndpoint = getApiUrl('/users/$userId/authenticators/$authId/', {
    path: {userId: 'me', authId},
  });
  const enrollEndpoint = getApiUrl('/users/$userId/authenticators/$interfaceId/enroll/', {
    path: {userId: 'me', interfaceId: authId},
  });

  const pendingInvitation = useMemo(getPendingInvite, []);

  const {
    data: authenticator,
    error,
    isError,
    isPending,
    refetch,
  } = useApiQuery<Authenticator>([enrollEndpoint], {
    staleTime: 0,
  });

  const authenticatorName = authenticator?.name ?? 'Authenticator';

  const alreadyEnrolled =
    error?.status === 400 && error.responseJSON?.details === 'Already enrolled';

  const {mutateAsync: enrollAsync} = useMutation({
    mutationFn: (data: EnrollPayload) =>
      fetchMutation({url: enrollEndpoint, method: 'POST', data}),
  });

  useEffect(() => {
    if (!isError) {
      return;
    }

    if (alreadyEnrolled) {
      navigate('/settings/account/security/');
      addErrorMessage(t('Already enrolled'));
    }
  }, [alreadyEnrolled, error, isError, navigate]);

  // Handler when we successfully add a 2fa device
  const handleEnrollSuccess = useCallback(async () => {
    // If we're pending approval of an invite, the user will have just joined
    // the organization when completing 2fa enrollment. We should reload the
    // organization context in that case to assign them to the org.
    if (pendingInvitation) {
      await fetchOrganizationByMember(api, pendingInvitation.memberId.toString(), {
        addOrg: true,
        fetchOrgDetails: true,
      });
    }

    navigate('/settings/account/security/');
    openRecoveryOptions({authenticatorName});

    // The remainder of this function is included primarily to smooth out the relocation flow. The
    // newly claimed user will have landed on `https://sentry.io/settings/account/security` to
    // perform the 2FA registration. But now that they have in fact registered, we want to redirect
    // them to the subdomain of the organization they are already a member of (ex:
    // `https://my-2fa-org.sentry.io`), but did not have the ability to access due to their previous
    // lack of 2FA enrollment.
    let orgs = OrganizationsStore.getAll();
    if (orgs.length === 0) {
      // Try to load orgs post 2FA again.
      orgs = await fetchOrganizations(api, {member: '1'});
      OrganizationsStore.load(orgs);

      // Still no orgs? Nowhere to redirect the user to, so just stay in place.
      if (orgs.length === 0) {
        return;
      }
    }

    // If we are already in an org sub-domain, we don't need to do any redirection. If we are not
    // (this is usually only the case for a newly claimed relocated user), we redirect to the org
    // slug's subdomain now.
    const isAlreadyInOrgSubDomain = orgs.some(org => {
      return org.links.organizationUrl === new URL(window.location.href).origin;
    });
    if (!isAlreadyInOrgSubDomain) {
      testableWindowLocation.assign(generateOrgSlugUrl(orgs[0]!.slug));
    }
  }, [api, authenticatorName, navigate, pendingInvitation]);

  // Handler when we failed to add a 2fa device
  const handleEnrollError = useCallback(() => {
    setIsMutationPending(false);
    addErrorMessage(t('Error adding %s authenticator', authenticatorName));
  }, [authenticatorName]);

  const handleSmsReset = useCallback(() => {
    setHasSentCode(false);
    refetch();
  }, [refetch]);

  // Handles SMS authenticators
  const handleSmsSubmit = useCallback(
    async (value: {otp: string; phone: string}, formApi: {reset: () => void}) => {
      const {phone, otp} = value;

      // Don't submit if empty
      if (!phone || !authenticator) {
        return;
      }

      const data = {
        phone,
        // Make sure `otp` is undefined if we are submitting OTP verification
        // Otherwise API will think that we are on verification step (e.g. after submitting phone)
        otp: hasSentCode ? otp : undefined,
        secret: authenticator.secret,
      };

      // Only show loading when submitting OTP
      setSendingCode(!hasSentCode);

      if (hasSentCode) {
        addLoadingMessage(t('Verifying OTP...'));
      } else {
        addLoadingMessage(t('Sending code to %s...', data.phone));
      }

      try {
        await enrollAsync(data);
      } catch {
        formApi.reset();

        addErrorMessage(hasSentCode ? t('Incorrect OTP') : t('Error sending SMS'));

        setHasSentCode(false);
        setSendingCode(false);

        // Re-fetch a fresh secret
        refetch();

        return;
      }

      if (hasSentCode) {
        // OTP was accepted and SMS was added as a 2fa method
        handleEnrollSuccess();
      } else {
        // Just successfully finished sending OTP to user
        setHasSentCode(true);
        setSendingCode(false);
        addSuccessMessage(t('Sent code to %s', data.phone));
      }
    },
    [authenticator, enrollAsync, handleEnrollSuccess, hasSentCode, refetch]
  );

  // Currently only TOTP uses this
  const handleTotpSubmit = useCallback(
    async (value: {otp: string}) => {
      if (!authenticator) {
        return;
      }

      setIsMutationPending(true);

      try {
        await enrollAsync({...value, secret: authenticator.secret});
      } catch (err) {
        handleEnrollError();
        return;
      }

      handleEnrollSuccess();
    },
    [authenticator, enrollAsync, handleEnrollError, handleEnrollSuccess]
  );

  // Handle webAuthn
  const handleWebAuthn = useCallback(
    async (value: {challenge: string; deviceName: string; response: string}) => {
      setIsMutationPending(true);

      try {
        await enrollAsync(value);
      } catch (err) {
        handleEnrollError();
        return;
      }

      handleEnrollSuccess();
    },
    [enrollAsync, handleEnrollError, handleEnrollSuccess]
  );

  // Removes an authenticator
  const handleRemove = useCallback(async () => {
    if (!authenticator?.authId) {
      return;
    }

    // `authenticator.authId` is NOT the same as `useParams().authId` This is
    // for backwards compatibility with API endpoint
    try {
      await api.requestPromise(authenticatorEndpoint, {method: 'DELETE'});
    } catch (err) {
      addErrorMessage(t('Error removing authenticator'));
      return;
    }

    navigate('/settings/account/security/');
    addSuccessMessage(t('Authenticator has been removed'));
  }, [api, authenticator?.authId, authenticatorEndpoint, navigate]);

  if (isMutationPending || isPending || alreadyEnrolled) {
    return <LoadingIndicator />;
  }
  if (isError) {
    if (error.status === 404) {
      return <NotFound />;
    }
    if (error.status === 403) {
      return (
        <LoadingError message={t('You do not have permission to view this page.')} />
      );
    }
    return <LoadingError message={error.message} onRetry={refetch} />;
  }

  if (!authenticator) {
    return null;
  }

  const isActive = authenticator.isEnrolled || authenticator.status === 'rotation';

  return (
    <SentryDocumentTitle title={t('Security')}>
      <SettingsPageHeader
        title={<AuthenticatorHeader name={authenticator.name} isActive={isActive} />}
        action={
          authenticator.isEnrolled &&
          authenticator.removeButton && (
            <RemoveConfirm onConfirm={handleRemove}>
              <Button variant="danger">{authenticator.removeButton}</Button>
            </RemoveConfirm>
          )
        }
      />

      <TextBlock>{authenticator.description}</TextBlock>

      {authenticator.rotationWarning && authenticator.status === 'rotation' && (
        <Alert.Container>
          <Alert variant="warning">{authenticator.rotationWarning}</Alert>
        </Alert.Container>
      )}

      {!!authenticator.form?.length && authenticator.id === 'totp' && (
        <TotpEnrollForm authenticator={authenticator} onSubmit={handleTotpSubmit} />
      )}
      {!!authenticator.form?.length && authenticator.id === 'sms' && (
        <SmsEnrollForm
          authenticator={authenticator}
          hasSentCode={hasSentCode}
          sendingCode={sendingCode}
          onReset={handleSmsReset}
          onSubmit={handleSmsSubmit}
        />
      )}
      {!!authenticator.form?.length && authenticator.id === 'u2f' && (
        <U2fEnrollForm authenticator={authenticator} onSubmit={handleWebAuthn} />
      )}
    </SentryDocumentTitle>
  );
}
